### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/akari-bot#939]
- [x]  weekly_rss 拆分为独立schedule和hook调用
- [x]  bots/scheduler 与 bots/api 合并
- [x]  当子bot独立运行时自动引入 scheduler 部分函数以维持功能正常运作/禁用 restart 命令
